### ISSUE TITLE
Does Poutine work on Windows?

### ISSUE THREAD

**Issue by corneliusroemer** [Peter-Two-Point-O/POUTINE#7]
We've had a bug report for treetime from a user who tried to run Poutine on Windows.

They managed to get Poutine to work on Linux. Does Poutine support Windows? I couldn't find this in your docs, maybe worth adding!

**Comment by Peter-Two-Point-O** [comment]
I sent that particular user your way because the issue the user was having was not specifically related to POUTINE but to treetime.  They were not able to get treetime working as a command-line program on Windows.  So the question is, does treetime work on Windows?  We did not see any mention of that in the treetime docs.  POUTINE should work on a Windows box, but we haven't tried installing treetime on Windows yet since none of us use Windows.  So maybe you and the Neher lab can let us know if treetime can be used as a command-line program in Windows.  The non-treetime portion of POUTINE definitely does work on any platform that supports Java (which is basically every platform).

**Comment by corneliusroemer** [comment]
I've figured out a way to get the CLI command to work cross platform (I
think). Let's see whether the PR gets merged and then one can try again.
Until then it's unfortunately non-windows (WSL should work).
